export const F1_CONSTANTS = {
  AVERAGE_PILOT_REACTION: 200,
  MIN_REACTION_TIME: 50,
  MAX_REACTION_TIME: 1000,

  LIGHT_SEQUENCE_INTERVAL: 1000,
  EXTINCTION_MIN_DELAY: 1000,
  EXTINCTION_MAX_DELAY: 4000,

  FREQUENCY_RED_LIGHT: 760,
  FREQUENCY_EXTINCTION: 1200,
  FREQUENCY_ERROR: 300,
  FREQUENCY_SUCCESS: 1600,

  DURATION_RED_LIGHT: 200,
  DURATION_EXTINCTION: 150,
  DURATION_ERROR: 400,
  DURATION_SUCCESS: 250,

  TYRE_MIN_TEMP: 40,
  TYRE_OPTIMAL_MIN: 80,
  TYRE_OPTIMAL_MAX: 105,
  TYRE_MAX_TEMP: 120,
  TYRE_COOLING_AMOUNT: 15,
  TYRE_UPDATE_INTERVAL: 500,

  SCORE_IN_GREEN_ZONE: 10,
  SCORE_OUT_ZONE: 2,
  DIFFICULTY_INCREASE_INTERVAL: 30,

  STORAGE_REACTION_HIGH_SCORE: 'f1_high_score',
  STORAGE_TYRE_HIGH_SCORE: 'f1_tyre_high_score',
};
